package net.htmlcsjs.coffeeFloppa.commands;

import discord4j.core.object.entity.Message;
import net.htmlcsjs.coffeeFloppa.helpers.ExecHelper;

import java.io.FileOutputStream;
import java.net.URL;
import java.nio.channels.Channels;
import java.nio.channels.ReadableByteChannel;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.Arrays;

public class EvalCommand implements ICommand{
    @Override
    public String getName() {
        return "eval";
    }

    @Override
    public String execute(Message message) {
        String verb = message.getContent().split(" ")[1];
        String[] splitArg = message.getContent().split(" ");
        String arg = String.join(" ", Arrays.copyOfRange(splitArg, 2, splitArg.length));
        if (verb.equalsIgnoreCase("run")) {
            String code = "";
            if (message.getAttachments().size() > 0) {
                String data;
                try {
                    URL url = new URL(message.getAttachments().get(0).getUrl());
                    ReadableByteChannel readableByteChannel = Channels.newChannel(url.openStream());
                    FileOutputStream fileOutputStream = new FileOutputStream("dirty.py");
                    fileOutputStream.getChannel().transferFrom(readableByteChannel, 0, Long.MAX_VALUE);
                    fileOutputStream.close();

                    data = Files.readString(Path.of("dirty.py"));
                } catch (Exception e) {
                    e.printStackTrace();
                    return "an error occurred";
                }

                code = data.replace("`", "");
            } else {
                code = arg.replace("`", "");
            }

            return ExecHelper.execString(code, message);
        } else if (verb.equalsIgnoreCase("help")) {
            return """
                    This command can be used to run python code with the verb `run`, with more coming soon
                    **run:**
                     - you can attach attach a python file to run or provide it after the verb inside or out of `codeblocks`
                     - print out "$attach" followed by the file name to attach any files generated by your code
                     - imports and attaching files from outside of the run dir is disallowed
                     - default imports: math, numpy as np, pandas as pd, matplotlib.pyplot as plt, copy, random
                     """;
        }
        return "Invalid input";
    }
}
